# Generated by Django 6.1 on 2026-08-12 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapy', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='goal',
            name='psychologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_goals', to='users.psychologistprofile'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='therapy.goal'),
        ),
        migrations.AddField(
            model_name='task',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='therapysession',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='therapysession',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.psychologistprofile'),
        ),
        migrations.AddField(
            model_name='task',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='therapy.therapysession'),
        ),
    ]
