# Generated by Django 6.1 on 2026-08-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='current_score',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='goal',
            name='initial_score',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_score',
            field=models.IntegerField(default=10),
        ),
    ]
