# Generated by Django 6.1 on 2026-08-12 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0003_goal_current_score_goal_initial_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapysession',
            name='call_had_both',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapysession',
            name='patient_in_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapysession',
            name='psychologist_in_call',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SessionWebRTCSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_role', models.CharField(max_length=20)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webrtc_signals', to='therapy.therapysession')),
            ],
            options={
                'db_table': 'session_webrtc_signals',
                'ordering': ['created_at'],
            },
        ),
    ]
