# Generated by Django 6.1 on 2026-08-12 18:35

from django.db import migrations, models


def sync_existing_call_states(apps, schema_editor):
    TherapySession = apps.get_model('therapy', 'TherapySession')
    for session in TherapySession.objects.all():
        if session.status == 'completed':
            session.call_state = 'completed'
            session.patient_in_call = False
            session.psychologist_in_call = False
            session.call_had_both = False
        elif session.patient_in_call and session.psychologist_in_call:
            session.call_state = 'active'
        elif session.patient_in_call:
            session.call_state = 'patient_waiting'
        elif session.psychologist_in_call:
            session.call_state = 'psychologist_waiting'
        else:
            session.call_state = 'scheduled'
        session.save(update_fields=[
            'call_state', 'patient_in_call', 'psychologist_in_call', 'call_had_both'
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0004_session_call_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapysession',
            name='call_state',
            field=models.CharField(choices=[('scheduled', 'Planlaşdırılıb'), ('patient_waiting', 'Pasiyent gözləyir'), ('psychologist_waiting', 'Psixoloq gözləyir'), ('active', 'Canlı'), ('completed', 'Bitdi')], default='scheduled', max_length=30),
        ),
        migrations.RunPython(sync_existing_call_states, migrations.RunPython.noop),
    ]
