# Generated by Django 6.1 on 2026-08-12 19:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0005_session_call_state_field'),
        ('users', '0002_multi_psychologist_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalProgressLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='therapy.goal')),
            ],
            options={
                'db_table': 'goal_progress_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('achieved_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='users.patientprofile')),
            ],
            options={
                'db_table': 'patient_achievements',
                'ordering': ['-achieved_at'],
            },
        ),
        migrations.CreateModel(
            name='TherapyLearning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnings', to='users.patientprofile')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learnings', to='therapy.therapysession')),
            ],
            options={
                'db_table': 'therapy_learnings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TherapyTimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='users.patientprofile')),
                ('psychologist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='users.psychologistprofile')),
            ],
            options={
                'db_table': 'therapy_timeline_events',
                'ordering': ['-event_date'],
            },
        ),
    ]
