# Generated by Django 6.1 on 2026-08-12 18:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


def migrate_psychologist_fk_to_assignments(apps, schema_editor):
    PatientProfile = apps.get_model('users', 'PatientProfile')
    PatientPsychologistAssignment = apps.get_model('users', 'PatientPsychologistAssignment')
    for patient in PatientProfile.objects.exclude(psychologist_id=None):
        PatientPsychologistAssignment.objects.get_or_create(
            patient_id=patient.id,
            psychologist_id=patient.psychologist_id,
            defaults={'is_active': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPsychologistAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychologist_assignments', to='users.patientprofile')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_assignments', to='users.psychologistprofile')),
            ],
            options={
                'verbose_name': 'Pasiyent-Psixoloq əlaqəsi',
                'verbose_name_plural': 'Pasiyent-Psixoloq əlaqələri',
                'db_table': 'patient_psychologist_assignments',
                'unique_together': {('patient', 'psychologist')},
            },
        ),
        migrations.RunPython(migrate_psychologist_fk_to_assignments, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='patientprofile',
            name='psychologist',
        ),
    ]
