# Generated by Django 6.1 on 2026-08-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='checkin_type',
            field=models.CharField(default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='checkin',
            name='emotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='emotion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='event',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.CharField(default='clinical', max_length=20),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='mood_score',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
