# Generated by Django 6.1 on 2026-08-12 19:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_checkin_cause_checkin_checkin_type_checkin_emotion_and_more'),
        ('therapy', '0005_session_call_state_field'),
        ('users', '0002_multi_psychologist_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='therapy.therapysession'),
        ),
        migrations.AddField(
            model_name='note',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='therapy.therapysession'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='materials/%Y/%m/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('audio', 'Audio'), ('video', 'Video'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='users.psychologistprofile')),
            ],
            options={
                'db_table': 'materials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='content.material')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_materials', to='users.patientprofile')),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_materials', to='users.psychologistprofile')),
            ],
            options={
                'db_table': 'patient_materials',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ThoughtRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('situation', models.TextField()),
                ('automatic_thought', models.TextField()),
                ('emotion', models.CharField(max_length=100)),
                ('intensity', models.IntegerField(default=5)),
                ('alternative_thought', models.TextField(blank=True, null=True)),
                ('cognitive_distortion', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thoughts', to='users.patientprofile')),
            ],
            options={
                'db_table': 'thought_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
