# Generated by Django 6.1 on 2026-08-12 17:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_concern', models.TextField(blank=True, null=True)),
                ('therapy_experience', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_format', models.CharField(default='online', max_length=20)),
                ('preferred_language', models.CharField(default='az', max_length=10)),
                ('mental_health_history', models.TextField(blank=True, null=True)),
                ('stress_level', models.IntegerField(blank=True, null=True)),
                ('sleep_quality', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Onboarding Qiymətləndirilməsi',
                'verbose_name_plural': 'Onboarding Qiymətləndirilmələri',
                'db_table': 'onboarding_assessments',
            },
        ),
    ]
