# Generated by Django 6.1 on 2026-08-12 18:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingassessment',
            name='anxiety_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingassessment',
            name='boundaries_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingassessment',
            name='desired_change',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingassessment',
            name='life_difficulties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingassessment',
            name='main_concern',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingassessment',
            name='relationships_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingassessment',
            name='self_confidence_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingassessment',
            name='stress_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingassessment',
            name='therapy_expectation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingassessment',
            name='therapy_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PatientConnectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Gözləyir'), ('accepted', 'Qəbul edilib'), ('rejected', 'Rədd edilib')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests', to='users.patientprofile')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests', to='users.psychologistprofile')),
            ],
            options={
                'db_table': 'patient_connection_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
